[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
HighPrecisionArithmetic = "694c1f89-4b53-5470-8b3e-767244e2eb4d"

[compat]
Documenter = "1"
julia = "1.11"

[sources]
HighPrecisionArithmetic = {path = ".."}
