name: Documentation

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:

permissions:
  actions: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1' 
      - uses: julia-actions/cache@v2
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.resolve(); Pkg.instantiate()'
      - name: Run tests 
        run: julia --threads=auto --project=. -e 'using Pkg; Pkg.test()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # For authentication with SSH deploy key
        run: julia --threads=auto --project=docs/ docs/make.jl
